// 10 películas por género y hacer primero 10 animación / 10 anime / 10 romance / 10 western / 10 cine mudo

// el primero es una guía, seguir ese formato y escribir todo es minúscula

// no tocar la propiedad boobleano: true
var data = [{
  'titulo': 'Guardians of the Galaxy Vol. 2',
  'año': '2017',
  'duracion': '136 min',
  'genero': 'Action, Adventure, Sci-Fi',
  'director': 'James Gunn',
  'escritor': 'James Gunn, Dan Abnett (based on the Marvel comics by), Andy Lanning (based on the Marvel comics by), Steve Englehart (Star-lord created by), Steve Gan (Star-lord created by), Jim Starlin (Gamora and Drax created by), Stan Lee (Groot created by), Larry Lieber (Groot created by), Jack Kirby (Groot created by), Bill Mantlo (Rocket Raccoon created by), Keith Giffen (Rocket Raccoon created by), Steve Gerber (Howard the Duck created by), Val Mayerik (Howard the Duck created by)',
  'actores': 'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel',
  'puntuacion': '7.8',
  'tipo': 'movie',
  'inversion': '$389,804,217',
  'produccion': 'Walt Disney Pictures',
  'booleano': 'true',
  'sinapsis': '250 caracteres',
  'idioma': 'ingles', 
  'image': ''
},
{
  'titulo': 'cantando bajo la lluvia',
  'año': '1952',
  'duracion': '103 minutos',
  'genero': 'musical',
  'director': 'stanley donen, gene kelly',
  'escritor': 'betty comden, adolph green',
  'puntuacion': '7.6',
  'tipo': 'pelicula',
  'inversion': '$ 2 540 000',
  'produccion': 'arthur freed',
  'booleano': 'true',
  'sinapsis': 'antes de conocer a la aspirante a actriz kathy, don lockwood pensaba que lo tenía todo pero cuando la conoce, se da cuenta que ella es lo que le faltaba. don quiere filmar musicales con kathy, pero se interpone la reina del cine mudo lina lamont.',
  'idioma': 'inglés',
  'image': 'http://cinetecaalameda.net/sitio/wp-content/uploads/2016/08/Cantando1.jpg'
},
{
  'titulo': 'grease',
  'año': '1978',
  'duracion': '110 minutos',
  'genero': 'musical',
  'director': 'randal kleiser',
  'escritor': 'jim jacobs, bronte woodard',
  'puntuacion': '8.7',
  'tipo': 'película',
  'inversion': '$6 000 000',
  'produccion': 'rso records',
  'booleano': 'true',
  'sinapsis': 'sandy y danny han pasado un romántico verano juntos, pero, cuando las vacaciones se acaban, sus caminos se separan. vuelven a verse en el instituto rydell, pero danny ya no es el chico encantador y atento; ahora es engreído e insensible.',
  'idioma': 'inglés',
  'image': 'https://images-na.ssl-images-amazon.com/images/M/MV5BOTIyODkzOTE1NF5BMl5BanBnXkFtZTcwNTg2Njk0Mw@@._V1_SY1000_CR0,0,677,1000_AL_.jpg'
},
{
  'titulo': '',
  'año': '',
  'duracion': '',
  'genero': '',
  'director': '',
  'escritor': '',
  'puntuacion': '',
  'tipo': '',
  'inversion': '',
  'produccion': '',
  'booleano': 'true',
  'sinapsis': '250 caracteres',
  'idioma': ''
},
{
  'titulo': '',
  'año': '',
  'duracion': '',
  'genero': '',
  'director': '',
  'escritor': '',
  'puntuacion': '',
  'tipo': '',
  'inversion': '',
  'produccion': '',
  'booleano': 'true',
  'sinapsis': '250 caracteres',
  'idioma': ''
},
{
  'titulo': '',
  'año': '',
  'duracion': '',
  'genero': '',
  'director': '',
  'escritor': '',
  'puntuacion': '',
  'tipo': '',
  'inversion': '',
  'produccion': '',
  'booleano': 'true',
  'sinapsis': '250 caracteres',
  'idioma': ''
},
{
  'titulo': '',
  'año': '',
  'duracion': '',
  'genero': '',
  'director': '',
  'escritor': '',
  'puntuacion': '',
  'tipo': '',
  'inversion': '',
  'produccion': '',
  'booleano': 'true',
  'sinapsis': '250 caracteres',
  'idioma': ''
},
{
  'titulo': '',
  'año': '',
  'duracion': '',
  'genero': '',
  'director': '',
  'escritor': '',
  'puntuacion': '',
  'tipo': '',
  'inversion': '',
  'produccion': '',
  'booleano': 'true',
  'sinapsis': '250 caracteres',
  'idioma': ''
},
{
  'titulo': '',
  'año': '',
  'duracion': '',
  'genero': '',
  'director': '',
  'escritor': '',
  'puntuacion': '',
  'tipo': '',
  'inversion': '',
  'produccion': '',
  'booleano': 'true',
  'sinapsis': '250 caracteres',
  'idioma': ''
},
{
  'titulo': '',
  'año': '',
  'duracion': '',
  'genero': '',
  'director': '',
  'escritor': '',
  'puntuacion': '',
  'tipo': '',
  'inversion': '',
  'produccion': '',
  'booleano': 'true',
  'sinapsis': '250 caracteres',
  'idioma': ''
},
{
  'titulo': '',
  'año': '',
  'duracion': '',
  'genero': '',
  'director': '',
  'escritor': '',
  'puntuacion': '',
  'tipo': '',
  'inversion': '',
  'produccion': '',
  'booleano': 'true',
  'sinapsis': '250 caracteres',
  'idioma': ''
},
{
  'titulo': '',
  'año': '',
  'duracion': '',
    'genero': '',
    'director': '',
    'escritor': '',
    'puntuacion': '',
    'tipo': '',
    'inversion': '',
    'produccion': '',
    'booleano': 'true',
    'sinapsis': '250 caracteres',
    'idioma': ''
  },
  {
    'titulo': '',
    'año': '',
    'duracion': '',
    'genero': '',
    'director': '',
    'escritor': '',
    'puntuacion': '',
    'tipo': '',
    'inversion': '',
    'produccion': '',
    'booleano': 'true',
    'sinapsis': '250 caracteres',
    'idioma': ''
  },
  {
    'titulo': '',
    'año': '',
    'duracion': '',
    'genero': '',
    'director': '',
    'escritor': '',
    'puntuacion': '',
    'tipo': '',
    'inversion': '',
    'produccion': '',
    'booleano': 'true',
    'sinapsis': '250 caracteres',
    'idioma': ''
  },
  {
    'titulo': '',
    'año': '',
    'duracion': '',
    'genero': '',
    'director': '',
    'escritor': '',
    'puntuacion': '',
    'tipo': '',
    'inversion': '',
    'produccion': '',
    'booleano': 'true',
    'sinapsis': '250 caracteres',
    'idioma': ''
  },
  {
    'titulo': '',
    'año': '',
    'duracion': '',
    'genero': '',
    'director': '',
    'escritor': '',
    'puntuacion': '',
    'tipo': '',
    'inversion': '',
    'produccion': '',
    'booleano': 'true',
    'sinapsis': '250 caracteres',
    'idioma': ''
  },
  {
    'titulo': '',
    'año': '',
    'duracion': '',
    'genero': '',
    'director': '',
    'escritor': '',
    'puntuacion': '',
    'tipo': '',
    'inversion': '',
    'produccion': '',
    'booleano': 'true',
    'sinapsis': '250 caracteres',
    'idioma': ''
  },
  {
    'titulo': '',
    'año': '',
    'duracion': '',
    'genero': '',
    'director': '',
    'escritor': '',
    'puntuacion': '',
    'tipo': '',
    'inversion': '',
    'produccion': '',
    'booleano': 'true',
    'sinapsis': '250 caracteres',
    'idioma': ''
  },
  {
    'titulo': '',
    'año': '',
    'duracion': '',
    'genero': '',
    'director': '',
    'escritor': '',
    'puntuacion': '',
    'tipo': '',
    'inversion': '',
    'produccion': '',
    'booleano': 'true',
    'sinapsis': '250 caracteres',
    'idioma': ''
  },
  {
  'titulo': '',
  'año': '',
  'duracion': '',
  'genero': '',
  'director': '',
  'escritor': '',
  'puntuacion': '',
  'tipo': '',
  'inversion': '',
  'produccion': '',
  'booleano': 'true',
  'sinapsis': '250 caracteres',
  'idioma': ''
},
{
  'titulo': '',
  'año': '',
  'duracion': '',
  'genero': '',
  'director': '',
  'escritor': '',
  'puntuacion': '',
  'tipo': '',
  'inversion': '',
  'produccion': '',
  'booleano': 'true',
  'sinapsis': '250 caracteres',
  'idioma': ''
}
];