var data = [
  {
    'titulo': 'Los años maravillosos',
    'año': '1988',
    'duracion': '22-24 min',
    'genero': 'Comedia dramática',
    'director': 'Neal Marlens & Carol Black',
    'escritor': 'Neal Marlens & Carol Black',
    'temporadas': '6',
    'episodios': '115',
    'cadenaoriginal': 'ABC',
    'booleano': 'true',
    'sinapsis': 'Estuvo seis temporadas en antena, en la cadena estadounidense de televisión ABC, de 1988 a 1993. TV Guide nombró al programa como uno de los 20 mejores de la década de 1980. Después de sólo seis episodios emitidos, ganó un Emmy por mejor serie de comedia en 1988',
    'video': 'https://www.youtube.com/embed/QqNUePCICG8',
    'imagen': 'https://img.peru21.pe/files/ec_article_multimedia_gallery/uploads/2017/08/09/598b92ae148ae.jpeg'
  },
  {
    'titulo': 'Alf',
    'año': '1986',
    'duracion': '30 min',
    'genero': 'Comedia, ciencia ficcion',
    'director': 'Bernie Brillstein, Tom Patchell',
    'escritor': 'Tom Patchell, Paul Fusco',
    'temporadas': '4',
    'episodios': '102',
    'cadenaoriginal': 'NBC',
    'booleano': 'true',
    'sinapsis': ' ALF es una serie de televisión estadounidense, que se emitió originalmente por la NBC entre el 22 de septiembre de 1986 y 24 de marzo de 1990. La serie constó de 102 episodios, tras los cuales se presentó una película, llamada Proyecto: ALF, que contaba el desenlace de la historia. ',
    'video': 'https://www.youtube.com/embed/RjWYNI1wBi4',
    'imagen': 'http://images.mentalfloss.com/sites/default/files/styles/mf_image_3x2/public/alf-header.jpg?itok=e0I9JTFd&resize=1100x740'
  },
  {
    'titulo': 'El auto fantastico',
    'año': '1982',
    'duracion': '60 min',
    'genero': 'accion',
    'director': 'Glen A. Larson',
    'escritor': 'Glen A. Larson',
    'temporadas': '4',
    'episodios': '90',
    'cadenaoriginal': 'NBC',
    'booleano': 'true',
    'sinapsis': 'Knight Rider (conocida como El coche fantástico en España, El auto increíble en México y El auto fantástico en el resto de Hispanoamérica) fue una serie de televisión estadounidense de los años 1980. El personaje protagonista de la serie, Michael Knight (interpretado por el actor David Hasselhoff), es un defensor de los pobres y desamparados, cuyo nombre real es Michael Long, que combate la injusticia conduciendo un prototipo de automóvil de alta tecnología.',
    'video': 'https://www.youtube.com/embed/St_yo2glyeE',
    'imagen': 'https://i.ytimg.com/vi/z6piLz5-0p8/maxresdefault.jpg'
  },
  {
    'titulo': 'Cosby Show',
    'año': '1984',
    'duracion': '24 min',
    'genero': 'Comedia',
    'director': 'Marcy Carsey, Tom Werner',
    'escritor': 'Marcy Carsey, Tom Werner',
    'temporadas': '8',
    'episodios': '197',
    'cadenaoriginal': 'NBC',
    'booleano': 'true',
    'sinapsis': 'The Cosby Show (La hora de Bill Cosby en España) es una serie de televisión norteamericana protagonizada por Bill Cosby. Se estrenó en Estados Unidos en 1984 en el canal NBC. Narra la vida de los Huxtable, una familia afroamericana de clase media-alta que vive en el barrio de Brooklyn de Nueva York.',
    'video': 'https://www.youtube.com/embed/ubkpnXTamI0',
    'imagen': 'https://www.bet.com/celebrities/news/2016/11/14/cosby-show/_jcr_content/image.custom0x0.dimg/__1479154213425__1479152381607/111416-celebs-cosby-show.jpg'
  },
  {
    'titulo': 'Los magnificos',
    'año': '1983',
    'duracion': '50 min',
    'genero': 'Accion',
    'director': 'John Ashley',
    'escritor': '	Stephen J. Cannell y Frank Lupo',
    'temporadas': '5',
    'episodios': '98',
    'cadenaoriginal': 'NBC',
    'booleano': 'true',
    'sinapsis': '(El equipo A en España y Los magníficos o Brigada A en Hispanoamérica) es una serie de televisión estadounidense, protagonizada por George Peppard, Dwight Schultz, Dirk Benedict y Mr. T, que fue emitida originalmente por la cadena NBC, desde el 23 de enero de 1983 hasta el 8 de marzo de 1987.',
    'video': 'https://www.youtube.com/embed/aJqU19ZMjAA',
    'imagen': 'https://i.ytimg.com/vi/y1MbnLiUW9o/maxresdefault.jpg'
  },
  {
    'titulo': 'tres por tres',
    'año': '1987',
    'duracion': '30 min',
    'genero': 'Comedia',
    'director': 'Jeff Franklin',
    'escritor': 'Jeff Franklin',
    'temporadas': '8',
    'episodios': '192',
    'cadenaoriginal': 'ABC',
    'booleano': 'true',
    'sinapsis': 'Full House (Padres forzosos en España y Tres por tres en Latinoamérica) es una serie de televisión estadounidense creada por Jeff Franklin para la cadena televisiva ABC. Ambientada en San Francisco, California, muestra las crónicas de un padre viudo; "Danny Tanner", quien, después de la muerte de su esposa "Pam", reúne a su mejor amigo "Joey Gladstone" y su cuñado "Jesse Katsopolis" para ayudar a criar a sus 3 hijas: "D.J.", "Stephanie", y "Michelle". ',
    'video': 'https://www.youtube.com/embed/b0RXacIj-KY',
    'imagen': 'https://img.elcomercio.pe/files/ec_article_multimedia_gallery/uploads/2017/09/22/59c5638356db3.jpeg'
  },
  {
    'titulo': 'Star Trek',
    'año': '1966',
    'duracion': '40 min',
    'genero': 'Ficcion',
    'director': 'Gene Roddenberry',
    'escritor': 'Gene Roddenberry',
    'temporadas': '30',
    'episodios': '733',
    'cadenaoriginal': 'NBC',
    'booleano': 'true',
    'sinapsis': 'La trama de las series y películas de Star Trek es bastante sobria en cuanto al futuro de la humanidad, consistente en cuanto a la calidad de la historia, coherente por la continuidad de la misma y congruente con la forma de ser de los humanos actuales (que intenta demostrar que el hombre no cambiará mucho en los próximos 400 años), siempre con la «continua misión de explorar extraños, nuevos mundos, y de buscar nuevas formas de vida y nuevas civilizaciones, viajando audazmente a donde nadie ha llegado antes».',
    'video': 'https://www.youtube.com/embed/ZLlV_JVtO5c',
    'imagen': 'http://www.startrekdesktopwallpaper.com/new_wallpaper/Star_Trek_OriginalSerie_Crew2013_freecomputerdesktopwallpaper_1920.jpg'
  },
  {
    'titulo': 'Murder, She Wrote',
    'año': '1984',
    'duracion': '30 min',
    'genero': 'Accion',
    'director': 'Angela Lansbury',
    'escritor': 'Peter S. Fisher',
    'temporadas': '12',
    'episodios': '264',
    'cadenaoriginal': 'CBS',
    'booleano': 'true',
    'sinapsis': 'La protagonista es Jessica Beatrice Fletcher (interpretada por Angela Lansbury), una profesora de inglés que, tras jubilarse y ante el fallecimiento de su esposo, se lanza a la aventura de ser escritora de novelas de misterio, alcanzado el éxito como J. B. Fletcher.',
    'video': 'https://www.youtube.com/embed/68shcoLWgiU',
    'imagen': 'https://img.buzzfeed.com/buzzfeed-static/static/2015-07/17/21/campaign_images/webdr14/how-would-you-die-on-murder-she-wrote-2-6305-1437181784-1_dblbig.jpg'
  },
  {
    'titulo': 'Miami Vice',
    'año': '1984',
    'duracion': '48 mins',
    'genero': 'Comedia accion',
    'director': 'Michael Man',
    'escritor': 'Anthony Yerkovich',
    'temporadas': '5',
    'episodios': '11',
    'cadenaoriginal': 'NBC',
    'booleano': 'true',
    'sinapsis': 'Miami Vice (en España: Corrupción en Miami; en Hispanoamérica: División Miami, Vicio en Miami o Miami, Policía Especial) es una serie de televisión estadounidense producida por Michael Mann para la NBC. La serie se caracterizó por su novedosa integración de música y efectos visuales para narrar la historia. Miami Vice estaba protagonizada por Don Johnson y Philip Michael Thomas, que interpretaban a dos detectives del Departamento de Policía del condado de Miami-Dade, que trabajaban encubiertos en Miami. ',
    'video': 'https://www.youtube.com/embed/X-WmnbVAe8I',
    'imagen': 'https://seriesblanco.com/files/noticias/1781.jpg'
  },
  {
    'titulo': 'La pequeña maravilla',
    'año': '1989',
    'duracion': '30 min',
    'genero': 'Comedia',
    'director': 'Budd Grossman',
    'escritor': 'Howard Leeds',
    'temporadas': '4',
    'episodios': '96',
    'cadenaoriginal': 'Redifusion',
    'booleano': 'true',
    'sinapsis': 'La historia gira en torno a V.I.C.I. (Voice Input Child Identicant) interpretado por Tiffany Brissette, un androide con forma de niña de 10 años creado como un proyecto personal y en absoluto secreto por Ted Lawson (Dick Christie), quien trabaja para la empresa cibernética United Robotronics.',
    'video': 'https://www.youtube.com/embed/NpSss40-JBc',
    'imagen':
    'https://cde.peru.com//ima/0/1/0/7/3/1073400/924x530/pequena-maravilla.jpg'
  },
  {
    'titulo': 'Hechizada',
    'año': '1964',
    'duracion': '40 min',
    'genero': 'comedia romantica',
    'director': 'Jerry Davis',
    'escritor': 'Sol Saks',
    'temporadas': '8',
    'episodios': '254',
    'cadenaoriginal': 'ABC',
    'booleano': 'true',
    'sinapsis': 'Darrin Stephens es un joven publicista que se enamora de Samantha, una bella y dulce joven. Samantha y Darrin se casan, pero durante su luna de miel ella le confiesa que es una bruja, y desde ese momento pasan extrañas y divertidas situaciones a causa de sus poderes.',
    'video': 'https://www.youtube.com/embed/HalktotKGMQ',
    'imagen': 'https://www.eluniverso.com/sites/default/files/styles/nota_ampliada_normal_foto/public/fotos/2014/11/bewitched-e1398581750118.png?itok=F8DrgzNO'
  },
  {
    'titulo': 'The ThunderCats',
    'año': '1985',
    'duracion': '30 min',
    'genero': 'Ficcion',
    'director': 'Arthur Rankin, Jr.',
    'escritor': 'Bernard Hoffer',
    'temporadas': '4',
    'episodios': '130',
    'cadenaoriginal': 'Redifusion',
    'booleano': 'true',
    'sinapsis': 'Thundercats (estilizado como ThunderCats, conocida en España e Hispanoamérica como ThunderCats: Los felinos cósmicos) es una serie animada estadounidense de televisión que fue producida por Rankin/Bass Productions misma que creó a los Halcones Galácticos, Los Tigres del Mar, esta última fue creada como parte de la serie de libros de historietas.',
    'video': 'https://www.youtube.com/watch?v=5sYC--2CEhk',
    'imagen':
    'http://news.thundercats.ws/wp-content/uploads/sites/6/2011/03/Thundercats-Wallpaper-1-HD_1299385920.jpg'
  },
  {
    'titulo': 'Sailor Moon',
    'año': '1992',
    'duracion': '30 min',
    'genero': 'Comedia',
    'director': 'Junichi Sato',
    'escritor': 'Naoko Takeuchi',
    'temporadas': '18',
    'episodios': '12',
    'cadenaoriginal': 'Toei Animation',
    'booleano': 'true',
    'sinapsis': 'Pretty Soldier Sailor Moon (Bishōjo Senshi Sērā Mūn?), mejor conocida como Sailor Moon, es una serie de manga escrita e ilustrada por Naoko Takeuchi en 1992. El manga se hizo particularmente famoso por volver a popularizar con gran éxito el subgénero de las magical girls,4​ y sus elementos sentai consiguieron que la aceptación también fuese masiva entre el sector masculino, generalmente menos interesado en este tipo de historias.',
    'video': 'https://www.youtube.com/watch?v=JWKBwFOVvpw',
    'imagen':
    'https://dw9to29mmj727.cloudfront.net/promo/2016/5257-SeriesHeaders_SMv3_2000x800.jpg'
  },
  {
    'titulo': 'Marco',
    'año': '1976',
    'duracion': '30 min',
    'genero': 'Animacion',
    'director': 'Isao Takahata',
    'escritor': 'Isao Takahata',
    'temporadas': '1',
    'episodios': '52',
    'cadenaoriginal': 'Fuji Television',
    'booleano': 'true',
    'sinapsis': 'Marco (Haha wo tazunete sanzenri?) conocida como Tres mil leguas en busca de mamá, o también como De los Apeninos a los Andes, es una serie de anime japonesa basada en el relato Marco, de los Apeninos a los Andes incluido en la novela italiana Corazón de Edmondo de Amicis.',
    'video': 'https://www.youtube.com/watch?v=OPsQQFakmmA',
    'imagen':
    'https://i2.wp.com/freakelitex.com/wp-content/uploads/2016/11/Marco.jpg?resize=590%2C434'
  },
  {
    'titulo': 'Super Campeones',
    'año': '1983',
    'duracion': '30 min',
    'genero': 'Animacion',
    'director': 'Isamu Imakake',
    'escritor': 'Yōichi Takahashi',
    'temporadas': '1',
    'episodios': '37',
    'cadenaoriginal': 'TV Tokyo',
    'booleano': 'true',
    'sinapsis': 'Captain Tsubasa (Kyaputen Tsubasa?) (literalmente en español Tsubasa 翼 - Alas), es un manga creado en 1981 por el historietista japonés Yōichi Takahashi. El anime de la serie fue conocido en Hispanoamérica como Super campeones y en España como Campeones: Oliver y Benji.',
    'video': 'https://www.youtube.com/watch?v=jOppIgxfOw0',
    'imagen':
    'http://i.espectaculos.televisa.com/2017/12/super-campeones.jpg'
  },
  {
    'titulo': 'Baywatch',
    'año': '1989',
    'duracion': '30 min',
    'genero': 'Accion',
    'director': 'Seth Gordon',
    'escritor': 'Damian Shannon',
    'temporadas': '11',
    'episodios': '242',
    'cadenaoriginal': 'NBC',
    'booleano': 'true',
    'sinapsis': 'La historia gira en torno a V.I.C.I. (Voice Input Child Identicant) interpretado por Tiffany Brissette, un androide con forma de niña de 10 años creado como un proyecto personal y en absoluto secreto por Ted Lawson (Dick Christie), quien trabaja para la empresa cibernética United Robotronics.',
    'video': 'https://www.youtube.com/watch?v=VzAwJe_dsS0',
    'imagen':
    'http://i2.mirror.co.uk/incoming/article10421869.ece/ALTERNATES/s615b/PROD-BAYWATCH.jpg'
  },
  {
    'titulo': 'He-Man',
    'año': '1983',
    'duracion': '22 min',
    'genero': 'Animacion',
    'director': 'Gwen Wetzler',
    'escritor': 'Mattel',
    'temporadas': '2',
    'episodios': '130',
    'cadenaoriginal': 'Redifusion',
    'booleano': 'true',
    'sinapsis': 'He-Man and The Masters of The Universe, conocida como He-Man y los Amos del Universo en Latinoamérica y en España, es una serie de televisión animada estadounidense producida por Filmation basado en línea de juguetes de Mattel Masters of The Universe.',
    'video': 'https://www.youtube.com/watch?v=ymwNiut3Yxwc',
    'imagen':
    'https://i.kinja-img.com/gawker-media/image/upload/s--FQm_C0YB--/c_scale,fl_progressive,q_80,w_800/hx6qx4ido3sic06fffvw.jpg'
  }
];